name: Build LaTeX documents
on:
  push:
    paths:
    - .github/workflows/build_tex.yml
    - tex/**

  pull_request:
    paths:
    - .github/workflows/build_tex.yml
    - tex/**

  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v4

    - name: Install Poetry
      run: pipx install poetry

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: poetry

    - name: Install local package
      run: |
        poetry install
        source $(poetry env info --path)/bin/activate

    - name: Compile LaTeX documents
      uses: xu-cheng/texlive-action@v2
      with:
        run: |
          apk add make
          cd tex/
          make pdf -j$(nproc)

    - name: Zip files
      run: |
        cd tex/
        make zip

    - name: Archive exercise files
      uses: actions/upload-artifact@v4
      with:
        name: tex-documents
        path: tex/pdfs.zip
